# Generated by Django 5.2.12 on 2026-03-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tasks",
            index=models.Index(
                fields=["user", "-priority", "-date_added"],
                name="tasks_tasks_user_id_df8d53_idx",
            ),
        ),
    ]
