# Generated by Django 6.0.1 on 2026-01-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("compted", "Completed"),
                ],
                default="medium",
                max_length=64,
            ),
        ),
    ]
