# Generated by Django 6.0.1 on 2026-01-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_tasks_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"ordering": ["-priority", "-date_added"]},
        ),
        migrations.AlterField(
            model_name="tasks",
            name="priority",
            field=models.CharField(
                choices=[("1", "Low"), ("2", "Medium"), ("3", "High")],
                default="1",
                max_length=64,
            ),
        ),
    ]
