# Generated by Django 6.0.1 on 2026-01-27 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_tasks_options_alter_tasks_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tasks",
            unique_together={("task", "user")},
        ),
    ]
